### ISSUE TITLE
Release, installation instructions

### ISSUE THREAD

**Issue by lemna** [giabaio/survHE#14]
Hi Gianluca,

the zip file in the release is a zip of the source - it can't be installed using install.packages under windows. 

What a windows user needs is either one the artifacts compiled by appveyor - binary, compiled versions of the package. If you upload one / both to the release area, the installation instructions are very brief:

> Under windows, type `install.packages("https://github.com/giabaio/survHE/archive/1.0.4.zip", repos = NULL, dependencies = "Suggests")` to install the package and its dependencies.

In this case there would be no need for Rtools or installing dependencies manually. That is only needed when installing it as a source package.

Peter.

**Comment by giabaio** [comment]
Hi Peter,
Thanks. Will fix later (although I think it does not let you upload two
files for the same release - - - one for i386 and one for x64 - - - so I'll
probably just make my life easier and upload the artifacts on my website
and link to them)...

Gianluca


On 10 Jan 2017 7:14 a.m., "Peter Konings" <notifications@github.com> wrote:

Hi Gianluca,

the zip file in the release is a zip of the source - it can't be installed
using install.packages under windows.

What a windows user needs is either one the artifacts compiled by appveyor
- binary, compiled versions of the package. If you upload one / both to the
release area, the installation instructions are very brief:

Under windows, type install.packages("https://github.com/giabaio/survHE/
archive/1.0.4.zip", repos = NULL, dependencies = "Suggests") to install the
package and its dependencies.

In this case there would be no need for Rtools or installing dependencies
manually. That is only needed when installing it as a source package.

Peter.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/giabaio/survHE/issues/14>, or mute the thread

**Comment by giabaio** [comment]
And actually, I'm testing this using the artifact created by appveyor, but *unless I'm doing something stupid on the Windows VM they provide at work*, 
`install.packages("survHE_1.0.4.zip", repos = NULL, dependencies = "Suggests")` or `dependencies="Depends"` or even `dependencies=TRUE` does *not* install the dependencies --- package 
`‘survHE’ successfully unpacked and MD5 sums checked` 
but then 
`library(survHE)` 
returns 
`Error: package ‘flexsurv’ required by ‘survHE’ could not be found`

Have you tested that you can actually install the dependencies automatically using the compiled binary?

**Comment by lemna** [comment]
Not on a clean system unfortunately - I have flexsurv et al. installed. 

I did not realize that `install.packages` ignores `dependencies` if `repos = NULL`. That is very annoying. Possible solutions:

- have the users install the dependencies manually, as before. At least this does not require Rtools.
- provide a script to do this, like the inla and bioconductor projects do. See [Duncan Murdoch's post](http://r.789695.n4.nabble.com/Windows-GUI-quot-Install-Packages-from-local-zip-files-quot-and-dependencies-td848173.html) for some ideas.
- provide a cran-like structure to point `repos` to (see the thread above, or [drat](https://github.com/eddelbuettel/drat) for a relatively easy way to do this on github or your website)

I think that a simple script pointing to your website would be a good compromise. I can send you one tonight.

**Comment by giabaio** [comment]
I've had a little play around with this. I think the simplest option for me to maintain (for not at least!) is to use a standalone webpage for `survHE` where I upload the binary files for the current release and then provide a script, something like `INLA` used to do, eg
``` R
source("www.statistica.it/gianluca/survHE/giveme_survHE.R")
```
or making clear in the `README.Rmd` file what the procedures are (ie through `devtools` or by first installing the dependencies + the zip file from the website).

Sounds reasonable?

**Comment by lemna** [comment]
Yes, that's probably the easiest. The script above might be a good start: it first installs survHE, then checks dependencies and installs any missing.

**Comment by giabaio** [comment]
I've updated the `README.md` file - the instruction should be clear now. I've tested on the VM and it all seems to work. Of course, on a machine with a basic R install, this takes quite some time...

Shout if there's anything else that doesn't add up!
Thanks
