### ISSUE TITLE
testing Gompertz assumptions fails

### ISSUE THREAD

**Issue by lemna** [giabaio/survHE#9]
Hi Gianluca,

I'm trying to get rid of all the warnings in the build process. One of those is for `test.linear.assumptions()`, caused by the code for testing a Gompertz model. It actually fails when using it on a Gompertz model:

```r
> mle <- fit.models(formula = Surv(recyrs, censrec) ~ group,
+                   data = bc,
+                   distr = "gompertz",
+                   method = "mle")
> mle

Model fit for the Gompertz model, obtained using Flexsurvreg 
(Maximum Likelihood Estimate). Running time: 0.070 seconds

                 mean        se      L95%      U95%
shape       0.1314578 0.0380993 0.0567846 0.2061310
rate        0.0440407 0.0075254 0.0315069 0.0615605
groupMedium 0.8371064 0.1713208 0.5013238 1.1728889
groupPoor   1.6217065 0.1648660 1.2985751 1.9448378

Model fitting summaries
Akaike Information Criterion (AIC)....: 1658.772
Bayesian Information Criterion (BIC)..: 1676.895

> test.linear.assumptions(mle)
Error in test.linear.assumptions(mle) : object 'V2' not found
```
What is the intention of the graphic? hazard vs. time, but only when the hazard != 0?

I've been working on this function a bit more yesterday, and I'd be happy to submit a PR with a fix if you explain what the output should be.

Thanks,
Peter.

**Comment by giabaio** [comment]
Peter,
Thanks. *At the moment*, the `survHE` function `test.linear.assumptions()` can only assess this for a limited selection of models (Exp, Weibull, log-Logistic and log-Normal). So the Gompertz fails because it's simply not implemented --- I think what happens is that an object `V2` is not created, because the distributional assumption is not valid. 

Will and I have only started playing around with this (as part of his MSc dissertation) and, as I said, the function needs some more work (that's why it's not included in the [manual](https://github.com/giabaio/survHE/blob/master/inst/doc/survHE.pdf)). 

It would be good to have a bit more about this, in the general workflow of `survHE`, as when fitting general models it would be good to be able to provide a bit more testing... When I'm back after Christmas, I'll try and post some "roadmap" of future developments (which of course I'm happy to discuss and get input from modellers/people who can use `survHE` in their real work!).

Gianluca

**Comment by lemna** [comment]
I'm sorry, I didn't know this function was part of a thesis project. I propose to replace the Gompertz code by a placeholder for now, as this will allow us to build the package without a warning about the `V2` object. I'm looking forward to future additions by Will, and also to your roadmap.

Peter.

**Comment by giabaio** [comment]
Peter, 
Happy new year! This is very interesting --- I'm not a Windows user (or fan, for that matter... :-)) but it does help to have this. Does this automatically take care of all the dependencies as well?

Gianluca

**Comment by lemna** [comment]
Yes, it will. Travis and appveyor basically download and install everything from scratch, including R itself, whenever you commit anything. This serves as a test for your commits. You can even have appveyor push the finished binaries back to github where they will appear under a "Releases" tab (see [here](https://help.github.com/articles/creating-releases/)). A windows user can install such a zip file with `install.packages("survHE_1.0.4.zip", repos = NULL, depends = "Suggests")`, or using whatever interface is available in their editor. The only thing to be aware of is that r-appveyor builds with  the `--no-multiarch` option, so the user will need to select the correct version (x64 or i386) themselves.

I guess at some point you will need to provide these if you want to have survHE used outside academia. Many companies run windows and are not happy to provide access to a compiler.

Let me know if you want me to do a PR with functioning configuration files. Of course you'd have to sign up for these services (free for open source projects) and use your username instead of mine in the configuration.

Peter.

**Comment by giabaio** [comment]
Peter, 
that's interesting and helpful. Let me have a look and familiarise myself with appveyor, then we could do something like this. 

The plan is to make this available as widely as possible to all potential users and I will consider submitting to CRAN (which of course would get rid of the problem for Windows users) --- I've not done this yet, because I needed to polish the documentation. Also, the package is "heavy" (mostly because of the pre-compiled C++ code for Stan). 

But I think this is a very interesting way forward! Thanks for pointing it out!

**Comment by giabaio** [comment]
Incidentally, are you using a specific `appveyor.yml` file that enables you to build the package and then create the artefact?

**Comment by lemna** [comment]
Yes, take a look at the configuration that I use in my winbuild branch, tracking master: https://github.com/lemna/survHE/blob/winbuild/appveyor.yml
This is the result: https://ci.appveyor.com/project/lemna/survhe/build/1.0.51 .
It ran 2 jobs, one for 32 and one for 64 bit windows. There is one warning in the appveyor log that is unavoidable under windows as far as I know. This will not affect cran submission, as they crossbuild windows binaries under linux. I will add jobs that track r-develop, just like cran does.
The appveyor configuration is less strict than the travis configuration - it does not treat errors as warnings. The travis results are as close as you can get to cran.

**Comment by giabaio** [comment]
OK --- I think I got this. I've built the current version and created the zip files for both architectures. I need to decide what to do with them (possibly create a package website or may be have them downloadable from the GitHub repository). Will have to think about it (but suggestions welcome!).

**Comment by lemna** [comment]
I just did a PR, mainly to add shields to the frontpage and to add travis-ci.

I think making them available from github for now is the easiest thing to do. Maybe use Hadley Wickham's [pkgdown](http://hadley.github.io/pkgdown/) to add a basic website to this repository?
